### PR TITLE
Allow symfony 7

### PR DESCRIPTION
**Pull request by ehymel**

### CODE REVIEW

**Review by garak — CHANGES_REQUESTED** [review]
For the next time, it's a good habit to mention the issue solved by your PR.

About your proposed changes, let's remove support for Symfony 4. Supporting three versions of the framework is enough.

**Comment by ehymel** [comment]
Done for issue #83

**Review by garak — CHANGES_REQUESTED** [review]
You still need to remove the old versions of PHP/Symfony from the CI and to add the new ones.

**Comment by ehymel** [comment]
build.yaml updated to remove symfony 4.4 and add symfony 7

**Comment by ehymel** [comment]
The check fails due to lexik/form-filter-bundle not allowing php 8.2 (which is required for symfony 7). 

It seems that lexik/form-filter-bundle is abandoned with recommendation for a replacement, but I don't use the functionality that lexik/form-filter-bundle provides, so I have no interest in pursuing the replacement. Not sure how you'd like to handle.

**Comment by ehymel** [comment]
It seems lexik/form-filter-bundle has a version 8 that doesn't choke on php 8. After allowing this version the CI checks pass.

**Comment by BazylPL** [comment]
anything?

**Comment by garak** [comment]
Closing in favour of #91

**Pull request closed without merging**
